

server:
  port: 7100

logging:
  config: classpath:logback/logback-srping.xml
  level:
    root: info

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: localpw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  cloud:
    stream:
      binders:
        rabbit-binder:
          type: rabbit
          environment:
            spring.rabbitmq:
              host: localhost
              port: 5672
              username: ruser
              password: localpw
              virtual-host: legacy
      bindings:
        rabbit-binder-in:
          destination: user-topic
          binder: rabbit-binder
          group: notification-group