

server:
  port: 7100

logging:
  config: classpath:logback/logback-srping.xml
  level:
    root: info

spring:
  cloud:
    function:
      definition: consumeUserNotification
    stream:
      rabbit:
        bindings:
          consumeUserEmail-in-0:
            consumer: # 아래는 DLQ 설정
              republishToDlq: true
              deadLetterExchange: dlx-exchange
              deadLetterRoutingKey: dead-letter-key
      binders:
        rabbit-binder:
          type: rabbit
          environment:
            spring.rabbitmq:
              host: localhost
              port: 5672
              username: ruser
              password: localpw
              virtual-host: legacy
      bindings:
        consumeUserNotification-in-0:
          destination: user-topic
          binder: rabbit-binder
          group: notification-group
          contentType: application/json