services:
  redis-slave:
    image: redis:7.2-alpine
    container_name: redis-slave
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICA_IP=[Master Server IP]
    volumes:
      - ./data:/data
    command: ["redis-server", "--replicaof", "[Master Server IP]", "6379", "--replica-announce-ip", "[Slave Server IP]"]
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge