services:
  postgres-master:
    image: postgres:15
    container_name: postgres-master
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - ./data/master:/var/lib/postgresql/data
      - ./conf/master:/etc/postgresql/conf.d
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge