services:
  locust:
    image: locustio/locust:2.32.0
    command: >
      -f /mnt/locust/locustfile-v1.py --host=http://host.docker.internal:2343
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    networks:
      - locust-network

networks:
  locust-network:
    driver: bridge