

server:
  port: 7000


logging:
  config: classpath:logback/logback-srping.xml
  level:
    root: info
    org:
      elasticsearch: INFO
      elasticsearch.client: DEBUG
      org.apache.http: DEBUG

spring:
  elastic:
    url: ${Elastic_URL}
