services:
  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_DATABASE: test_db
      MYSQL_REPLICATION_MODE: slave
      MYSQL_MASTER_HOST: "192.168.0.138"  # Master 서버 IP
      MYSQL_REPLICATION_USER: replica_user
      MYSQL_REPLICATION_PASSWORD: replica_password
    ports:
      - "3309:3306"
    command: --server-id=2
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
      - ./back-up:/back-up  # 파일 복사가 필요하여 생성
networks:
  mysql-network:
    driver: bridge