services:
  redis-master:
    image: redis:7.2-alpine
    container_name: redis-docker-service
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge